/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/computer.glb 
Author: iammura (https://sketchfab.com/iammura)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pc-4719e3b31e4d4fc1a7e6341259abe5ef
Title: OLD PC
*/

import { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import * as THREE from "three"

gsap.registerPlugin(ScrollTrigger)

export function Computer(props) {
  const { nodes, materials } = useGLTF('/models/computer.glb')
  const groupRef = useRef(null)
  const { camera } = useThree()

  useLayoutEffect(() => {
    if (!groupRef.current) return

    groupRef.current.rotation.x = Math.PI / 7
    groupRef.current.rotation.y = -Math.PI / 4

    const initialCamera = { x: 0, y: 0.6, z: 7 }
    const finalCamera = { x: 0, y: 0.02, z: 2 }

    camera.position.set(initialCamera.x, initialCamera.y, initialCamera.z)
    camera.lookAt(0, 0, 0)
    camera.updateProjectionMatrix()

    const forward = new THREE.Vector3()
    camera.getWorldDirection(forward)

    forward.multiplyScalar(0) 

    const trigger = document.getElementById('scroll-area')
    if (!trigger) return

    const timeline = gsap.timeline({
      scrollTrigger: {
        trigger,
        start: 'top top',
        end: 'bottom bottom',
        scrub: 1,
      },
    })

    timeline
      .to(groupRef.current.rotation, { y: 0, duration: 1, ease: 'none' })
      .to(
        camera.position,
        {
          x: finalCamera.x,
          y: finalCamera.y,
          z: finalCamera.z,
          duration: 1,
          ease: 'none',
        },
        0
      )
      .to(groupRef.current.position, {
        x: forward.x,
        y: forward.y - .3,
        z: forward.z,
        duration: 1,
        ease: "none",
      }, 0)

    return () => {
      ScrollTrigger.getAll().forEach((instance) => instance.kill())
    }
  }, [camera])

  return (
    <group {...props} dispose={null} ref={groupRef} position={[0, 5, -20]} scale={0.3}>
      <group scale={0.01}>
        <group position={[66.388, 178.399, 235.798]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder024_Material018_0.geometry} material={materials['Material.018']} />
          <mesh geometry={nodes.Cylinder024_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[154.876, 28.771, 238.333]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube152_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube152_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube168_Material011_0.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Cube168_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[0, 264.313, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube175_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube175_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <group position={[0, 0, 202.393]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube151_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube151_Material_0.geometry} material={materials.Material} />
        </group>
        <group position={[0, 264.313, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube146_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube146_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube146_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube146_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Circle_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Circle_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Circle003_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Circle003_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube_Material010_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cube_Material016_0.geometry} material={materials['Material.016']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube111_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube111_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube111_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube115_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube115_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube115_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube115_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube113_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube113_Material_0.geometry} material={materials.Material} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube114_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube114_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube114_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube114_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-100.133, -48.886, 468.841]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube003_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube003_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-202.213, -47.605, 406.288]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube004_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube004_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-197.07, -47.605, 427.504]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube005_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube005_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-186.39, -47.605, 447.822]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube006_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube006_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-233.133, -47.605, 384.552]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube007_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube007_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-173.661, -47.605, 352.271]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube008_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Cube008_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube008_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-96.811, -47.605, 352.271]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube009_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube009_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-2.453, -47.605, 352.271]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube010_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube010_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[91.89, -47.605, 352.271]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube011_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube011_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[91.89, -47.605, 405.837]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube012_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube012_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[91.89, -47.605, 384.905]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube013_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube013_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[165.564, -47.605, 384.905]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube014_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube014_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[165.564, -47.605, 406.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube015_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube015_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[165.564, -47.605, 426.439]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube016_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube016_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[165.564, -47.605, 447.206]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube017_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube017_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[91.89, -47.605, 468.633]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube019_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube019_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[207.922, -47.605, 469.457]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube020_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube020_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[112.822, -47.605, 448.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube018_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube018_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[50.486, -47.605, 384.552]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube022_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube022_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[54.858, -47.605, 406.251]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube023_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube023_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[47.545, -47.605, 427.497]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube024_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube024_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[42.337, -47.605, 447.642]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube025_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube025_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-229.31, -47.605, 406.251]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube026_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube026_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-215.158, 0, 427.497]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube027_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube027_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-220.783, -47.605, 447.642]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube028_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube028_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[229.097, -47.605, 458.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube029_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube029_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[229.097, -47.605, 416.005]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube030_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube030_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[176.401, -47.605, 469.457]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube031_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Cube031_Material005_0.geometry} material={materials['Material.005']} />
        </group>
        <group position={[-26.549, -47.605, 469.457]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube032_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube032_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[55.051, -47.605, 469.457]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube033_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube033_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-198.617, -47.605, 469.457]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube034_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube034_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[-228.543, -47.605, 469.457]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube035_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube035_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <group position={[0, 0, 350.377]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube002_Material007_0.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Cube002_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cube002_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube002_Material008_0.geometry} material={materials['Material.008']} />
        </group>
        <group position={[48.356, 72.02, -216.579]} rotation={[-Math.PI, 0, 0]} scale={17.534}>
          <mesh geometry={nodes.Circle006_Material021_0.geometry} material={materials['Material.021']} />
          <mesh geometry={nodes.Circle006_Material012_0.geometry} material={materials['Material.012']} />
          <mesh geometry={nodes.Circle006_Material011_0.geometry} material={materials['Material.011']} />
          <mesh geometry={nodes.Circle006_Material022_0.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.Circle006_Material013_0.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.Circle006_Material023_0.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Circle006_Material014_0.geometry} material={materials['Material.014']} />
        </group>
        <group position={[0, 0, -164.508]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube137_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube137_Material019_0.geometry} material={materials['Material.019']} />
          <mesh geometry={nodes.Cube137_Material020_0.geometry} material={materials['Material.020']} />
          <mesh geometry={nodes.Cube137_Material011_0.geometry} material={materials['Material.011']} />
        </group>
        <group position={[21.513, -18.033, -164.508]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube138_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube138_Material024_0.geometry} material={materials['Material.024']} />
        </group>
        <group position={[21.513, -18.033, -164.508]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube139_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube139_Material024_0.geometry} material={materials['Material.024']} />
        </group>
        <group position={[0.451, -0.595, -206.475]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube140_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube140_Material011_0.geometry} material={materials['Material.011']} />
        </group>
        <group position={[111.66, 39.393, -212.247]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube157_Material016_0.geometry} material={materials['Material.016']} />
          <mesh geometry={nodes.Cube157_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <group position={[70.364, 45.955, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder012_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder012_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[70.364, 45.955, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder013_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder013_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-207.293, 7.415, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder017_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder017_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-237.085, 7.415, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder018_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder018_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-256.258, 7.415, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder019_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder019_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-285.895, 7.415, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder020_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder020_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-274.906, 27.121, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder021_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder021_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-217.478, 27.121, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder022_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder022_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[70.364, -58.521, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder014_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder014_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-406.712, -58.521, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder015_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder015_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[-406.712, 45.498, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder016_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder016_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[70.364, -58.521, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder023_Material017_0.geometry} material={materials['Material.017']} />
          <mesh geometry={nodes.Cylinder023_Material010_0.geometry} material={materials['Material.010']} />
        </group>
        <group position={[416.393, -49.135, 404.757]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube126_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube126_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube126_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <mesh geometry={nodes.Cube148_Material015_0.geometry} material={materials['Material.015']} position={[165.824, 50.245, 358.847]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder001_Material003_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder010_Material_0.geometry} material={materials.Material} position={[162.316, 193.024, 226.657]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube124_Material001_0.geometry} material={materials['Material.001']} position={[0, 264.313, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Circle004_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Circle005_Material007_0.geometry} material={materials['Material.007']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube144_Material015_0.geometry} material={materials['Material.015']} position={[165.824, 0, 358.847]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube154_Material005_0.geometry} material={materials['Material.005']} position={[-395.22, -68.807, 325.167]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Circle007_Material011_0.geometry} material={materials['Material.011']} position={[256.838, 57.918, -216.743]} rotation={[-Math.PI, 0, 0]} scale={17.534} />
        <mesh geometry={nodes.Cube132_Material011_0.geometry} material={materials['Material.011']} position={[187.868, 59.036, -207.579]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube133_Material010_0.geometry} material={materials['Material.010']} position={[0, -0.805, -345.312]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube134_Material010_0.geometry} material={materials['Material.010']} position={[0, 0, -345.312]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube141_Material011_0.geometry} material={materials['Material.011']} position={[81.369, -11.318, -208.229]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube142_Material001_0.geometry} material={materials['Material.001']} position={[81.369, -11.318, -215.758]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube163_Material007_0.geometry} material={materials['Material.007']} position={[-16.525, 23.87, -242.162]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube164_Material007_0.geometry} material={materials['Material.007']} position={[-35.358, 23.87, -242.162]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube166_Material001_0.geometry} material={materials['Material.001']} position={[20.35, 383.577, -4.985]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube169_Material011_0.geometry} material={materials['Material.011']} position={[61.705, 211.11, -321.536]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube170_Material011_0.geometry} material={materials['Material.011']} position={[61.705, 211.11, -207.579]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube173_Material010_0.geometry} material={materials['Material.010']} position={[-125.899, 151.142, -345.312]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube174_Material010_0.geometry} material={materials['Material.010']} position={[-125.899, 151.947, -345.312]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder003_Material001_0.geometry} material={materials['Material.001']} position={[0, -20.635, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder005_Material001_0.geometry} material={materials['Material.001']} position={[0, -20.635, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder006_Material001_0.geometry} material={materials['Material.001']} position={[0, -20.635, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder007_Material001_0.geometry} material={materials['Material.001']} position={[0, -20.635, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} position={[416.411, -65.992, 346.786]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane004_Material005_0.geometry} material={materials['Material.005']} position={[-207.293, 205.057, -213.895]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane005_Material001_0.geometry} material={materials['Material.001']} position={[202.701, 7.415, 333.906]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Plane007_Material001_0.geometry} material={materials['Material.001']} position={[-207.293, 205.057, -213.895]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube150_Material015_0.geometry} material={materials['Material.015']} position={[165.824, 50.245, 358.847]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Torus_Material009_0.geometry} material={materials['Material.009']} position={[0, -145.437, 388.668]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer.glb')
